### ISSUE TITLE
Double Free of Split Sibling InnerNode when Posting InnerSplitNode CAS Fails

### ISSUE THREAD

**Issue by wangziqi2016** [wangziqi2013/BwTree#51]
Though this bug has never caused a real bug in testing, I observed this with visual inspection.

The problem is as described in the title. Since when CAS of InnerSplitNode fails, there will be a fake remove node created and linked to the new InnerNode and then put into epoch for recycling, we do not need to delete InnerNode because it will be soon removed by the GC thread. However in the current node the InnerNode is deleted.
, which causes a double free.

**Comment by wangziqi2016** [comment]
Since now we switch to preallocated storage we do not at all need to worry about this

**Comment by wangziqi2013** [comment]
No it's not true.
